// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

function classify(cell) {
  var match = typeof cell;
  if (match === "string") {
    return /* String */Block.__(1, [cell]);
  } else {
    return /* Int */Block.__(0, [cell]);
  }
}

var Cell = {
  classify: classify
};

function getAllValues(sheet) {
  return sheet.getDataRange().getValues();
}

exports.Cell = Cell;
exports.getAllValues = getAllValues;
/* No side effect */
