// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Tablecloth = require("tablecloth-bucklescript/src/tablecloth.bs.js");

function pick_columns(param, row) {
  return [
          Curry._1(row, {
                hd: param[0],
                tl: /* [] */0
              }),
          Curry._1(row, {
                hd: param[1],
                tl: /* [] */0
              })
        ];
}

function toMap(sheet) {
  var partial_arg = [
    0,
    1
  ];
  return Tablecloth.$$Array.map((function (param) {
                return pick_columns(partial_arg, param);
              }), sheet);
}

exports.pick_columns = pick_columns;
exports.toMap = toMap;
/* Tablecloth Not a pure module */
