// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Standard = require("reason-standard/bucklescript/src/Standard.bs.js");

function pick_columns(param, row) {
  return /* tuple */[
          Standard.$$Array.get(row, param[0]),
          Standard.$$Array.get(row, param[1])
        ];
}

function toMap(sheet) {
  var partial_arg = /* tuple */[
    0,
    1
  ];
  return Curry._1(Standard.$$Map.$$String.ofArray, Standard.$$Array.map(sheet, (function (param) {
                    return pick_columns(partial_arg, param);
                  })));
}

exports.pick_columns = pick_columns;
exports.toMap = toMap;
/* Standard Not a pure module */
